services:
  backend:
      build: ./backend
      command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
      ports:
        - "8000:8000"
      volumes:
        - ./backend:/app
      depends_on:
        - db
      environment:
        DATABASE_URL: "postgresql+asyncpg://my_app_user:secret@db/my_app_db"

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: my_app_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: my_app_db
    # Не нужно пробрасывать порты БД наружу,
    # т.к. 'backend' общается с 'db' по внутренней сети Docker

volumes:
  postgres_data: